module.exports ={
  userFormateError:{
    code:'10001',
    message:'用户名或密码为空',
    result:''
  },
  userAlreadyExists:{
    code:'10002',
    message:'用户已经存在',
    result:''
  },
  userRegisterError:{
    code:'10003',
    message:'用户注册错误',
    result:''
  }, 
  userIsNotExist:{
    code:'10004',
    message:'用户不存在',
    result:''
  },
  userLoginError:{
    code:'10005',
    message:'用户登录失败',
    result:""
  },
  invalidPassword:{
    code:'10006',
    message:'密码不匹配',
    result:""
  },
  tokenExporedError:{
    code:'10101',
    message:'token已过期',
    result:""
  },
  invalidToke:{
    code:'10102',
    message:"无效token",
    result:""
  },
  hasNotAdminPermission:{
    code:'10103',
    message:'没有管理员权限',
    result:""
  },
  fillUploadError:{
    code:'10201',
    message:'商品图片上传失败',
    result:''
  },
  filetypeUnsupported:{
    code:'10202',
    message:'不支持文件格式',
    result:''
  },
  goodsFormatError:{
    code:'10203',
    message:'商品参数类型错误',
    result:''
  },
  publishGoodsError:{
    code:'10204',
    message:'发布商品失败',
    result:''
  },
  invalidGoodsId:{
    code:'10205',
    message:'商品id不存在',
    result:''
  },
  cartsFormatError:{
    code:'10301',
    message:'传参格式错误',
    result:''
  },
  addrFormatError:{
    code:'10401',
    message:'地址传参格式错误',
    result:''
  },
  orderFormatError:{
    code:'10401',
    message:'订单传参格式错误',
    result:''
  },
}